In [4]:
import numpy as np

create a 1-D array with 16 elements of int type

In [9]:
arr = np.arange(16)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


 to reshape arr to 3-D

In [37]:
# to reshape arr to 3-D
arr = np.arange(16)
a = np.reshape(arr,(2,4,2))
print(a)
#size of the array
print(a.size)
# convert the array elements into float type
b= np.array(a,dtype=float)
print(b)
#to create identity 2-D
c= np.eye(2,dtype= int)
print(c)
#create a 2-D which consists of  first 10 even no :
d = np.arange(0,20,2)
print(d)
d1=np.reshape(d,(2,5))
print(d1)
d1[0]=[1,3,5,7,9]
print(d1)



e = np.array([[2,3,6],[7,8,9]])


[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]]
16
[[[ 0.  1.]
  [ 2.  3.]
  [ 4.  5.]
  [ 6.  7.]]

 [[ 8.  9.]
  [10. 11.]
  [12. 13.]
  [14. 15.]]]
[[1 0]
 [0 1]]
[ 0  2  4  6  8 10 12 14 16 18]
[[ 0  2  4  6  8]
 [10 12 14 16 18]]
[[ 1  3  5  7  9]
 [10 12 14 16 18]]


In [53]:
e = np.array([[2,3,6],[7,8,9]])
print(e)
print(e[:,1:])
f= np.cumsum(e)
print(f)
print(np.sum(e,axis=0))
print(np.max(e,axis=0))
print(np.max(e,axis=1))

[[2 3 6]
 [7 8 9]]
[[3 6]
 [8 9]]
[ 2  5 11 18 26 35]
[ 9 11 15]
[7 8 9]
[6 9]


In [1]:
import pandas